### ISSUE TITLE
Enhancement: Allow receiving binary data (e.g. images)

### ISSUE THREAD

**Issue by coyote1** [ioBroker/ioBroker.mqtt#115]
Bekomme von einer externen Anwendung ein Bild über MQTT geschickt. Die Daten des DP's sind aber falsch.
Werden die binären Daten in eine .jpg Datei geschrieben, ist die Datei nicht lesbar.
Testweise einen Mosquitto Broker installiert und über ioBroker mit node-red, die Daten vom Mosquitto Broker geholt und in eine .jpg Datei geschrieben. Das funktioniert einwandfrei.

siehe Thread: https://forum.iobroker.net/topic/38823/js-mqtt-dp-eines-bildes-jfif-in-datei-schreiben-jpg

**Versions:**  
 - Adapter version: 2.1.13
 - JS-Controller version: 3.1.6
 - Node version: 10.22.1
 - Operating system: Debian

**Comment by Apollon77** [comment]
I expect that the adapter expects to retrieve strings, and so a binary content "can only" break ...

**Comment by coyote1** [comment]
Hm ok, can you change this in the Adapter, so that we can use binary data?

**Comment by Apollon77** [comment]
No idea if "I" can do it ... For me personally I think the challenge is how to detect binary data vs string data ...

**Comment by Apollon77** [comment]
Ok, I need to see more infos. Please do

* Stop the adapter in Admin
* go to a shell
* run `DEBUG=mqtt-packet:writeToStream iobroker debug mqtt.0`

Then receive such an image and post the log please

**Comment by Apollon77** [comment]
PS: Yes in fact all data that are not boolean, number or string are converted to a string , so we would need to add binary detection and handling

**Comment by helmut64** [comment]
In my case I receive binary MQTT data (with zeros and other binary stuff) from my LoRa device, the reason for the binary data is that I need to have as short packets as possible. An interface like getting a binary buffer copy of the content with length would be helpful.
I debugged this some time ago at my friends ioBroker, however I don't habe a own ioBroker setup, which means I need to debug/test this at another installation.
Regards Helmut

**Comment by Apollon77** [comment]
For Interface: ioBroker has "binary States" and so it would be available that way I think

**Comment by GermanBluefox** [comment]
I can imagine, that after the topic received one time, the user can set manually ´common.type="binary"` and then ioBroker will save next state as binary state...

**Comment by helmut64** [comment]
For me the MQTT content must always be considered to be binary data. Later on the script must decide if it likes to process it as text, xml, json or whatever. It can be even binary data with an sound or image.

**Comment by Apollon77** [comment]
@helmut64 This breaks with the iobroker concept where binary is the absolute special case and "typed values" is the normal case (this also is proofed by  the long time this adapter now exists with that many active installation, and this topic was brought up by one user so far  :-)

**Comment by helmut64** [comment]
I know multiple users with this, of course many give up because it does not work with IOB.
Maybe there should be an API to get as well the RAW data @Apollon77
Again MQTT spec says binary arbitrary data.
PS: We are sending compressed records being forward from a LoRa radio messaging. In this case  every bytes counts because LoRa is 1200 baud only and we just forward this to MQTT.
We got also an MQTT Push Client app (www.radioshuttle.de) which supports binary as well. In our case we use a filter script option to process data.
PS: I am not an IOB user, I just got this problem on others and filed it here some years ago.
Regards Helmut @Apollon77

**Comment by Apollon77** [comment]
In general I could imaging the following options:
* An adapter settings that states "handle all data as binary data" ... Then effectively no adapter can really work with the data and only custom JavaScripts can process the data
* An adapter setting that allows to enter a "list of mqtt topics" that should be considered as binary. Then objects are created as binary, and rest stays "normal" (this would be the more convenient option then the idea from @GermanBluefox above to adjust objects afterwards which is still possible)
* Try to build a detection which handles "anything that looks like UTF-8 or ASCII" as normal state and all rest as binary - if binary one time (could maybe also happen because of bad connection we switch onject to binary ... has a lot of options to break especially because of such communication issues that could bring binary data where they should not be there

Any other?

**Comment by GermanBluefox** [comment]
Please test 4.0.0
https://github.com/ioBroker/ioBroker.mqtt#binary-messages
