### ISSUE TITLE
jarvis importer needs to have channel for the first directory in object structure

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.mqtt#278]
The importer of jarvis for MQTT need to have for the first directory of object structure. 
![image](https://user-images.githubusercontent.com/84818934/165367976-c6b9ddfe-4d5f-441d-8b5f-fddc31854da2.png)

It ist possible to integrate this in mqtt-Structure?
Thank you.

**Comment by Apollon77** [comment]
Because of the fact that "channel" has a semantic meaning and for MQTT this can not be automatically assumed thre are two options:

A: you manually changethe onbjects types from folder to channel
B: jarvis also accepts "folder" as an allowed structure element, but as said formally the "assumptions" would be different.

MQTT is kind of unstructured in a first place which makes this very problematic automatically
