### ISSUE TITLE
MQTT Adapter fails while receiving message with not printable chars

### ISSUE THREAD

**Issue by PapaSpik3** [ioBroker/ioBroker.mqtt#353]
**Describe the bug**  
MQTT Adapter fails while receiving message with not printable chars

**To Reproduce**  
Happens from time to time with the same client. I didnt find a way to reproduce.
Is client fault ofc but crashes the adapter.

**Expected behavior**  
remove not printable chars like � or □ from mqtt message before parsing.

**Screenshots & Logfiles**  
Client [PV-Garage] Cannot parse "pv/garage": {"InverterStatus":1,"InputPower":108.2,"PV1Voltage":74.4,"PV1InputCurrent":1.4,"PV1InputPower":108.2,<....>,"Energ1�  

**Versions:**  
 - Adapter version: 4.0.7
 - JS-Controller version: 4.0.23
 - Node version: v16.19.0
 - Operating system: buanet/iobroker:latest

**Additional context**  
In JS i use these regex to remove it: replace(/[^\x20-\x7E]/g, ''

**Comment by Apollon77** [comment]
Hm ... what about "making sure devices do not send such broken messages" or (if because of bad connection) then improve the connection situation? Because if we remove data then this means noone knows if the message is correct or not ... 

Also mqtt itself is a completely free format, so how we should at all detect in which messages these characters are invalid and in which not? The current logic assumes JSON when it is a string and start/end with the usual characters ... so it is still guessing ...

So whats the reason for these characters being there in your case?

**Comment by PapaSpik3** [comment]
Hello Apollon77,

it’s true is a misbehavior of the client and to fix that is principally the right way.

On the other hand it is a bit pity if a payload of a client could crash an adapter. If the adapter couldn’t handle all characters then they should be removed before parsing or the message should be dropped with a warning.

`Because if we remove data then this means noone knows if the message is correct or not ... ` you couldn’t use the data either if the adapter crashes  :-)

Maybe as option in the settings. Then everyone could decide if preventing crashes or unfiltered messages are more important.

Best regards

**Comment by Apollon77** [comment]
> On the other hand it is a bit pity if a payload of a client could crash an adapter.

It is not crashing, it is just an error logged ... SO it behaves as you say

**Comment by PapaSpik3** [comment]
Good Morning Apollon,

okay thanks for spending your Time :-)
Best regards
