### ISSUE TITLE
MQTT Adapter crash

### ISSUE THREAD

**Issue by vr6syncro** [ioBroker/ioBroker.mqtt#7]
Moin mein MQTT Adapter bekommt ein crash wenn sich ein bestimmter controller anmeldet:

```
host.ioBroker | 2017-12-05 18:57:16.429 | info | Restart adapter system.adapter.mqtt.0 because enabled
-- | -- | -- | --
host.ioBroker | 2017-12-05 18:57:16.429 | error | instance system.adapter.mqtt.0 terminated with code 0 (OK)
host.ioBroker | 2017-12-05 18:57:16.429 | error | Caught by controller[0]: at DestroyableTransform.onreadable (/opt/iobroker/node_modules/duplexify/index.js:127:10)
host.ioBroker | 2017-12-05 18:57:16.429 | error | Caught by controller[0]: at Connection.Duplexify._forward (/opt/iobroker/node_modules/duplexify/index.js:163:26)
host.ioBroker | 2017-12-05 18:57:16.429 | error | Caught by controller[0]: at Connection.Readable.push (/opt/iobroker/node_modules/readable-stream/lib/_stream_readable.js:157:10)
host.ioBroker | 2017-12-05 18:57:16.429 | error | Caught by controller[0]: at readableAddChunk (/opt/iobroker/node_modules/readable-stream/lib/_stream_readable.js:198:18)
host.ioBroker | 2017-12-05 18:57:16.429 | error | Caught by controller[0]: at Connection.emit (events.js:188:7)
host.ioBroker | 2017-12-05 18:57:16.429 | error | Caught by controller[0]: at emitOne (events.js:96:13)
host.ioBroker | 2017-12-05 18:57:16.429 | error | Caught by controller[0]: at Connection.emitPacket (/opt/iobroker/node_modules/mqtt-connection/connection.js:10:8)
host.ioBroker | 2017-12-05 18:57:16.429 | error | Caught by controller[0]: at Connection.emit (events.js:188:7)
host.ioBroker | 2017-12-05 18:57:16.429 | error | Caught by controller[0]: at emitOne (events.js:96:13)
host.ioBroker | 2017-12-05 18:57:16.429 | error | Caught by controller[0]: at Connection. (/opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:383:57)
host.ioBroker | 2017-12-05 18:57:16.428 | error | Caught by controller[0]: TypeError: Cannot read property 'toString' of undefined
mqtt.0 | 2017-12-05 18:57:15.919 | debug | onStateChange mqtt.0.info.connection: {"val":"","ack":true,"ts":1512496635917,"q":0,"from":"system.adapter.mqtt.0","lc":1512496635917}
mqtt.0 | 2017-12-05 18:57:15.919 | debug | stateChange mqtt.0.info.connection: {"val":"","ack":true,"ts":1512496635917,"q":0,"from":"system.adapter.mqtt.0","lc":1512496635917}
mqtt.0 | 2017-12-05 18:57:15.919 | debug | stateChange mqtt.0.last.will: {"val":"[object Object]","ack":true,"ts":1512496635917,"q":0,"from":"system.adapter.mqtt.0","lc":1512322544172}
mqtt.0 | 2017-12-05 18:57:15.918 | debug | onStateChange mqtt.0.info.connection: {"val":"Kueche1","ack":true,"ts":1512496635916,"q":0,"from":"system.adapter.mqtt.0","lc":1512496635916}
mqtt.0 | 2017-12-05 18:57:15.918 | debug | stateChange mqtt.0.info.connection: {"val":"Kueche1","ack":true,"ts":1512496635916,"q":0,"from":"system.adapter.mqtt.0","lc":1512496635916}
mqtt.0 | 2017-12-05 18:57:15.917 | debug | stateChange mqtt.0.last.will: {"val":"[object Object]","ack":true,"ts":1512496635915,"q":0,"from":"system.adapter.mqtt.0","lc":1512322544172}
mqtt.0 | 2017-12-05 18:57:15.916 | info | Client [Kueche1] closed
mqtt.0 | 2017-12-05 18:57:15.916 | info | Client [Kueche2] closed
mqtt.0 | 2017-12-05 18:57:15.916 | info | Client [Controller_4] closed
mqtt.0 | 2017-12-05 18:57:15.916 | error | TypeError: Cannot read property 'toString' of undefined at Connection. (/opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:383:57) at emitOne (events.js:96:13) at Connection
mqtt.0 | 2017-12-05 18:57:15.916 | error | uncaught exception: Cannot read property 'toString' of undefined
mqtt.0 | 2017-12-05 18:57:04.838 | debug | onStateChange mqtt.0.info.connection: {"val":"Kueche1,Kueche2","ack":true,"ts":1512496624835,"q":0,"from":"system.adapter.mqtt.0","lc":1512496624835}
mqtt.0 | 2017-12-05 18:57:04.838 | debug | stateChange mqtt.0.info.connection: {"val":"Kueche1,Kueche2","ack":true,"ts":1512496624835,"q":0,"from":"system.adapter.mqtt.0","lc":1512496624835}
mqtt.0 | 2017-12-05 18:57:04.837 | debug | onStateChange mqtt.0.info.connection: {"val":"Kueche1","ack":true,"ts":1512496624832,"q":0,"from":"system.adapter.mqtt.0","lc":1512496624832}
mqtt.0 | 2017-12-05 18:57:04.837 | debug | stateChange mqtt.0.info.connection: {"val":"Kueche1","ack":true,"ts":1512496624832,"q":0,"from":"system.adapter.mqtt.0","lc":1512496624832}


```

**Comment by vr6syncro** [comment]
hab den controller nochmals mit einer neuen fw beschrieben und bislang geht es.. komisch nur das ein externes gerät den adapter zum absturz bringen kann

**Comment by Alveran81** [comment]
Bei mir das gleiche. 

host.ioBroker-Pi | 2018-01-12 19:40:53.472 | info | Restart adapter system.adapter.mqtt.0 because enabled
-- | -- | -- | --
host.ioBroker-Pi | 2018-01-12 19:40:53.472 | error | instance system.adapter.mqtt.0 terminated with code 0 (OK)
host.ioBroker-Pi | 2018-01-12 19:40:53.472 | error | Caught by controller[0]: at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
host.ioBroker-Pi | 2018-01-12 19:40:53.472 | error | Caught by controller[0]: at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
host.ioBroker-Pi | 2018-01-12 19:40:53.472 | error | Caught by controller[0]: at Decoder. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
host.ioBroker-Pi | 2018-01-12 19:40:53.471 | error | Caught by controller[0]: at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
host.ioBroker-Pi | 2018-01-12 19:40:53.471 | error | Caught by controller[0]: at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
host.ioBroker-Pi | 2018-01-12 19:40:53.471 | error | Caught by controller[0]: at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
host.ioBroker-Pi | 2018-01-12 19:40:53.471 | error | Caught by controller[0]: at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
host.ioBroker-Pi | 2018-01-12 19:40:53.471 | error | Caught by controller[0]: at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
host.ioBroker-Pi | 2018-01-12 19:40:53.471 | error | Caught by controller[0]: at Socket. (/opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:70:41)
host.ioBroker-Pi | 2018-01-12 19:40:53.471 | error | Caught by controller[0]: at convertID2topic (/opt/iobroker/node_modules/iobroker.mqtt/lib/common.js:9:18)
host.ioBroker-Pi | 2018-01-12 19:40:53.470 | error | Caught by controller[0]: TypeError: Cannot read property 'substring' of undefined
mqtt.0 | 2018-01-12 19:40:52.955 | info | Client [esp826697fd77] closed
mqtt.0 | 2018-01-12 19:40:52.954 | error | TypeError: Cannot read property 'substring' of undefined at convertID2topic (/opt/iobroker/node_modules/iobroker.mqtt/lib/common.js:9:18) at Socket. (/opt/iobroker/node_modules/iobr
mqtt.0 | 2018-01-12 19:40:52.954 | error | uncaught exception: Cannot read property 'substring' of undefined
web.0 | 2018-01-12 19:40:43.911 | info | 2018-01-12T18:40:43.909Z Connected system.user.admin
sonoff.0 | 2018-01-12 19:40:35.271 | info | Client [Sonoff POW1] connected
mqtt.0 | 2018-01-12 19:40:31.663 | info | Client [esp826697fd77] subscribes on topic "RGBLED/action/set"
mqtt.0 | 2018-01-12 19:40:31.662 | info | publishOnSubscribe send all known states
mqtt.0 | 2018-01-12 19:40:31.662 | info | Client [esp826697fd77] subscribes on "RGBLED.led.+.set" with regex /mqtt\.0\.RGBLED\.led\.[^.]*\.set/
mqtt.0 | 2018-01-12 19:40:31.661 | info | Client [esp826697fd77] subscribes on "RGBLED.led.+.set" with regex /RGBLED\.led\.[^.]*\.set/
mqtt.0 | 2018-01-12 19:40:31.660 | info | Client [esp826697fd77] subscribes on topic "Lampen"
mqtt.0 | 2018-01-12 19:40:31.660 | info | publishOnSubscribe send all known states
mqtt.0 | 2018-01-12 19:40:31.660 | info | Client [esp826697fd77] subscribes on "RGBLED.relay.+.set" with regex /mqtt\.0\.RGBLED\.relay\.[^.]*\.set/
mqtt.0 | 2018-01-12 19:40:31.660 | info | Client [esp826697fd77] subscribes on "RGBLED.relay.+.set" with regex /RGBLED\.relay\.[^.]*\.set/
mqtt.0 | 2018-01-12 19:40:31.658 | info | publishOnSubscribe send all known states
mqtt.0 | 2018-01-12 19:40:31.656 | info | Client [esp826697fd77] subscribes on "RGBLED.channel.+.set" with regex /mqtt\.0\.RGBLED\.channel\.[^.]*\.set/
mqtt.0 | 2018-01-12 19:40:31.656 | info | Client [esp826697fd77] subscribes on "RGBLED.channel.+.set" with regex /RGBLED\.channel\.[^.]*\.set/
mqtt.0 | 2018-01-12 19:40:31.656 | info | Client [esp826697fd77] subscribes on topic "RGBLED/hsv/set"
mqtt.0 | 2018-01-12 19:40:31.656 | info | Client [esp826697fd77] subscribes on topic "RGBLED/rgb/set"
mqtt.0 | 2018-01-12 19:40:31.656 | info | Client [esp826697fd77] subscribes on topic "RGBLED/color/set"
mqtt.0 | 2018-01-12 19:40:31.655 | info | Client [esp826697fd77] subscribes on topic "RGBLED/kelvin/set"
mqtt.0 | 2018-01-12 19:40:31.655 | info | Client [esp826697fd77] subscribes on topic "RGBLED/mired/set"
mqtt.0 | 2018-01-12 19:40:31.655 | info | Client [esp826697fd77] subscribes on topic "RGBLED/brightness/set"
mqtt.0 | 2018-01-12 19:40:31.488 | info | Client [esp826697fd77] connected

**Comment by Apollon77** [comment]
So ich habe mal was eingebaut was diesen Fall abfängt und eine Fehlermeldung wirft, Dann sieht man ggf mehr.

Also: Bitte mal MQTT Adapter vom Github aktualisieren und dann das gleiche nochmal machen und log schicken!

**Comment by Alveran81** [comment]
Vielen Dank.
Jetzt sieht es so aus:


mqtt.0 | 2018-01-13 14:04:58.146 | info | Client [ESPURNA_97FD77] closed
-- | -- | -- | --
mqtt.0 | 2018-01-13 14:04:58.146 | error | TypeError: Cannot read property 'substring' of undefined at convertID2topic (/opt/iobroker/node_modules/iobroker.mqtt/lib/common.js:9:18) at Socket. (/opt/iobroker/node_modules/iobr
mqtt.0 | 2018-01-13 14:04:58.145 | error | uncaught exception: Cannot read property 'substring' of undefined
mqtt.0 | 2018-01-13 14:04:36.878 | info | Client [ESPURNA_97FD77] subscribes on topic "RGBLED/action/set"
mqtt.0 | 2018-01-13 14:04:36.878 | info | publishOnSubscribe send all known states
mqtt.0 | 2018-01-13 14:04:36.878 | info | Client [ESPURNA_97FD77] subscribes on "RGBLED.led.+.set" with regex /mqtt\.0\.RGBLED\.led\.[^.]*\.set/
mqtt.0 | 2018-01-13 14:04:36.878 | info | Client [ESPURNA_97FD77] subscribes on "RGBLED.led.+.set" with regex /RGBLED\.led\.[^.]*\.set/
mqtt.0 | 2018-01-13 14:04:36.878 | info | Client [ESPURNA_97FD77] subscribes on topic "Lampen"
mqtt.0 | 2018-01-13 14:04:36.878 | info | publishOnSubscribe send all known states
mqtt.0 | 2018-01-13 14:04:36.878 | info | Client [ESPURNA_97FD77] subscribes on "RGBLED.relay.+.set" with regex /mqtt\.0\.RGBLED\.relay\.[^.]*\.set/
mqtt.0 | 2018-01-13 14:04:36.878 | info | Client [ESPURNA_97FD77] subscribes on "RGBLED.relay.+.set" with regex /RGBLED\.relay\.[^.]*\.set/
mqtt.0 | 2018-01-13 14:04:36.877 | info | publishOnSubscribe send all known states
mqtt.0 | 2018-01-13 14:04:36.877 | info | Client [ESPURNA_97FD77] subscribes on "RGBLED.channel.+.set" with regex /mqtt\.0\.RGBLED\.channel\.[^.]*\.set/
mqtt.0 | 2018-01-13 14:04:36.877 | info | Client [ESPURNA_97FD77] subscribes on "RGBLED.channel.+.set" with regex /RGBLED\.channel\.[^.]*\.set/
mqtt.0 | 2018-01-13 14:04:36.877 | info | Client [ESPURNA_97FD77] subscribes on topic "RGBLED/hsv/set"
mqtt.0 | 2018-01-13 14:04:36.877 | info | Client [ESPURNA_97FD77] subscribes on topic "RGBLED/rgb/set"
mqtt.0 | 2018-01-13 14:04:36.877 | info | Client [ESPURNA_97FD77] subscribes on topic "RGBLED/color/set"
mqtt.0 | 2018-01-13 14:04:36.876 | info | Client [ESPURNA_97FD77] subscribes on topic "RGBLED/kelvin/set"
mqtt.0 | 2018-01-13 14:04:36.876 | info | Client [ESPURNA_97FD77] subscribes on topic "RGBLED/mired/set"
mqtt.0 | 2018-01-13 14:04:36.876 | info | Client [ESPURNA_97FD77] subscribes on topic "RGBLED/brightness/set"
mqtt.0 | 2018-01-13 14:04:36.645 | info | Client [ESPURNA_97FD77] connected

**Comment by Apollon77** [comment]
Versuche bitte nochmal. Habe erst 14:03 bemerkt das meine Änderungen nicht hochgeladen wurden :-(

**Comment by Alveran81** [comment]
Sieht besser aus


mqtt.0 | 2018-01-13 14:16:08.778 | error | Cannot resolve topic name for ID: undefined (object has no id): {"from":"system.host.ioBroker-Pi.cli","ts":1515007992628,"acl":{"object":1636,"owner":"system.user.admin","ownerGroup":"system.group.adm
-- | -- | -- | --
mqtt.0 | 2018-01-13 14:15:46.828 | info | Client [ESPURNA_97FD77] subscribes on topic "RGBLED/action/set"
mqtt.0 | 2018-01-13 14:15:46.827 | info | publishOnSubscribe send all known states

**Comment by Alveran81** [comment]
OK ID habe ich vergeben. Jetzt kommt wieder das:


mqtt.0 | 2018-01-13 14:19:03.221 | error | Cannot resolve topic name for ID: undefined (object has no id): {"from":"system.host.ioBroker-Pi.cli","ts":1515007992628,"acl":{"object":1636,"owner":"system.user.admin","ownerGroup":"system.group.adm
-- | -- | -- | --
mqtt.0 | 2018-01-13 14:18:47.568 | info | publishOnSubscribe

**Comment by Apollon77** [comment]
kannst Du es bitte mal ungekürzt aus dem Logfile unter /opt/iobroker/log/iobroker ... .log rauskopieren die "error"-zeile ?! Ist leider oben abgeschnitten

**Comment by Alveran81** [comment]
mqtt.0 | 2018-01-13 14:23:34.645 | info | Client [RGBLED] closed
-- | -- | -- | --
mqtt.0 | 2018-01-13 14:23:34.645 | error | Closed because of error
mqtt.0 | 2018-01-13 14:23:34.644 | warn | Client error [RGBLED]: Error: read ECONNRESET
mqtt.0 | 2018-01-13 14:23:21.976 | error | Cannot resolve topic name for ID: undefined (object has no id): {"from":"system.host.ioBroker-Pi.cli","ts":1515007992628,"acl":{"object":1636,"owner":"system.user.admin","ownerGroup":"system.group.adm
mqtt.0 | 2018-01-13 14:23:06.314 | info | publishOnSubscribe
mqtt.0 | 2018-01-13 14:23:06.313 | info | Client [RGBLED] subscribes on "mqtt.0.RGBLED.action.set"

**Comment by Apollon77** [comment]
Immer noch abgeschnitten :-(

**Comment by Alveran81** [comment]
Mehr steht nicht da.

Cannot resolve topic name for ID: undefined (object has no id): {"from":"system.host.ioBroker-Pi.cli","ts":1515007992628,"acl":{"object":1636,"owner":"system.user.admin","ownerGroup":"system.group.ad

**Comment by Alveran81** [comment]
Gefunden unter opt/iobroker/log

2018-01-13 14:28:19.923  - [31merror[39m: mqtt.0 Cannot resolve topic name for ID: undefined (object has no id): {"from":"system.host.ioBroker-Pi.cli","ts":1515007992628,"acl":{"object":1636,"owner":"system.user.admin","ownerGroup":"system.group.administrator"}}

**Comment by Alveran81** [comment]
Ich hoffe das stimmt. Sollten Standard Settings sein. 
![mqtt](https://user-images.githubusercontent.com/25667147/34906695-83774b9c-f872-11e7-9c3f-7721747f3b61.JPG)

**Comment by Apollon77** [comment]
Ich habe nochmal mehr log eingebaut. Am Ende ändert sich ein State wessen ID er nicht lesen kann. Ist das "*" bei "aske für die Bekanntgabe von eigenen States" wirklich sinnvoll? ioBroker hat viiiiiiiiele States ... Auch Spezielle ...

**Comment by Alveran81** [comment]
So habe geupdatet und der Log ist immer noch der gleiche.
2018-01-13 15:26:53.136  - [31merror[39m: mqtt.0 Cannot resolve topic name for ID: undefined (object has no id): {"from":"system.host.ioBroker-Pi.cli","ts":1515007992628,"acl":{"object":1636,"owner":"system.user.admin","ownerGroup":"system.group.administrator"}}

Was soll ich bei Maske * eintragen?

**Comment by Apollon77** [comment]
Das log gleich ist ist schonmal ok. Dann gab es keinen Fehler. 

Bei dem Feld sollte das rein was du an States selbst Publishen willst (do hatte ich es verstanden)

**Comment by Alveran81** [comment]
Sorry da hab ich mich falsch ausgedrückt. Der Fehler im Log ist der gleiche.
Aber er muss doch alle States publishen oder nicht?

mqtt.0 | 2018-01-13 15:29:30.893 | error | Cannot resolve topic name for ID: undefined (object has no id): {"from":"system.host.ioBroker-Pi.cli","ts":1515007992628,"acl":{"object":1636,"owner":"system.user.admin","ownerGroup":"system.group.ad
-- | -- | -- | --

**Comment by Apollon77** [comment]
Das hängt von deinem usecase ab. Welche iobroker States interessieren die anderen mqtt Geräte?

**Comment by Alveran81** [comment]
Andere iobroker States interessieren die anderen Geräte nicht. Nur jedes Gerät seine eigenen oder sehe ich das falsch?
Es scheint zu funktionieren. Also wenn ich werte am Gerät ändere(an,aus), ändern sich die Werte im iobroker unter mqqt.0/rgbled/relay/0 oder 1 zum Beispiel.

Wenn ich diese Werte im IObroker ändere sendet er diese aber nicht zurück an das Gerät.
Verstehe ich da etwas falsch oder muss dafür noch was eingestellt werden
Im Sonoff adapter funktioniert das so.

**Comment by Apollon77** [comment]
Jetzt ist die Frage wo die States in iobroker sind? Unter mqtt.0? Dann sollte im der konfig ein mqtt.0.* reichen.

**Comment by Alveran81** [comment]
Ja unter mqtt.0 siehe Bild. Aber irgendein Fehler steckt hier noch drin.
Wenn ich die Variable Lampen ändere(siehe Markierung im Bild) wird der Befehl gesendet und die Lampe schaltet. Alle anderen Befehle werden nicht gesendet. 
![mqtt](https://user-images.githubusercontent.com/25667147/34909110-8d55a0a4-f89b-11e7-95d8-5d5ad0e6f2fe.JPG)

**Comment by Apollon77** [comment]
was sagt debug log? Alle State-Änderungen sollten geloggt werden. hast Du jetzt mqtt.0.* drin stehen

**Comment by Alveran81** [comment]
Ja habe mqtt.0.* drin stehen auch mit nur * geht es nicht. Im normalen Log steht nichts. Gibt es einen speziellen Debug Log?

**Comment by Apollon77** [comment]
Im Admin unter Instanzen -> Expertenmodus. Dann kommt eine Spalte Loglevel... Dort debug wählen

**Comment by Alveran81** [comment]
Wenn ich Lampe schalte kommt das 

mqtt.0 | 2018-01-13 20:24:34.453 | debug | stateChange mqtt.0.RGBLED.Ankleide_Licht.relay.0: {"val":0,"ack":true,"ts":1515871474415,"q":0,"from":"system.adapter.mqtt.0","lc":1515871474415}
-- | -- | -- | --
mqtt.0 | 2018-01-13 20:24:34.453 | debug | stateChange mqtt.0.RGBLED.Ankleide_Licht.channel.4: {"val":255,"ack":true,"ts":1515871474413,"q":0,"from":"system.adapter.mqtt.0","lc":1515870729003}
mqtt.0 | 2018-01-13 20:24:34.452 | debug | stateChange mqtt.0.RGBLED.Ankleide_Licht.channel.3: {"val":255,"ack":true,"ts":1515871474411,"q":0,"from":"system.adapter.mqtt.0","lc":1515870729000}
mqtt.0 | 2018-01-13 20:24:34.452 | debug | stateChange mqtt.0.RGBLED.Ankleide_Licht.channel.2: {"val":0,"ack":true,"ts":1515871474409,"q":0,"from":"system.adapter.mqtt.0","lc":1515870711887}
mqtt.0 | 2018-01-13 20:24:34.451 | debug | stateChange mqtt.0.RGBLED.Ankleide_Licht.channel.1: {"val":0,"ack":true,"ts":1515871474408,"q":0,"from":"system.adapter.mqtt.0","lc":1515870711885}
mqtt.0 | 2018-01-13 20:24:34.451 | debug | stateChange mqtt.0.RGBLED.Ankleide_Licht.channel.0: {"val":0,"ack":true,"ts":1515871474406,"q":0,"from":"system.adapter.mqtt.0","lc":1515870565730}
mqtt.0 | 2018-01-13 20:24:34.450 | debug | stateChange mqtt.0.RGBLED.Ankleide_Licht.brightness: {"val":0,"ack":true,"ts":1515871474405,"q":0,"from":"system.adapter.mqtt.0","lc":1515870883485}
mqtt.0 | 2018-01-13 20:24:34.450 | debug | stateChange mqtt.0.RGBLED.Ankleide_Licht.hsv: {"val":"\u0000\u0000\u0000","ack":true,"ts":1515871474403,"q":0,"from":"system.adapter.mqtt.0","lc":1515870711880}
mqtt.0 | 2018-01-13 20:24:34.449 | debug | stateChange mqtt.0.RGBLED.Ankleide_Licht.rgb: {"val":"#000000","ack":true,"ts":1515871474402,"q":0,"from":"system.adapter.mqtt.0","lc":1515870711878}

Wenn ich nur ein und auschalten möchte das (also relay) das

mqtt.0 | 2018-01-13 20:25:51.907 | debug | onStateChange mqtt.0.RGBLED.Ankleide_Licht.relay.0: {"val":1,"ack":false,"ts":1515871551898,"q":0,"from":"system.adapter.admin.0","lc":1515871551898}
-- | -- | -- | --
mqtt.0 | 2018-01-13 20:25:51.907 | debug | stateChange mqtt.0.RGBLED.Ankleide_Licht.relay.0: {"val":1,"ack":false,"ts":1515871551898,"q":0,"from":"system.adapter.admin.0","lc":1515871551898}

**Comment by Alveran81** [comment]
Das ist eine RF Bridge, das gleiche wenn der IObroker sendet passiert 

mqtt.0 | 2018-01-13 20:28:50.944 | debug | onStateChange mqtt.0.RFBridge.relay.1: {"val":1,"ack":false,"ts":1515871730937,"q":0,"from":"system.adapter.admin.0","lc":1515871730937}
-- | -- | -- | --
mqtt.0 | 2018-01-13 20:28:50.943 | debug | stateChange mqtt.0.RFBridge.relay.1: {"val":1,"ack":false,"ts":1515871730937,"q":0,"from":"system.adapter.admin.0","lc":1515871730937}
mqtt.0 | 2018-01-13 20:28:50.942 | debug | redis pmessage io.mqtt.0.* io.mqtt.0.RFBridge.relay.1 {"val":1,"ack":false,"ts":1515871730937,"q":0,"from":"system.adapter.admin.0","lc":1515871730937}

Empfangen geht aber auch hier:
mqtt.0 | 2018-01-13 20:30:17.841 | debug | stateChange mqtt.0.RFBridge.relay.1: {"val":1,"ack":true,"ts":1515871817836,"q":0,"from":"system.adapter.mqtt.0","lc":1515871730937}
-- | -- | -- | --
mqtt.0 | 2018-01-13 20:30:17.840 | debug | redis pmessage io.mqtt.0.* io.mqtt.0.RFBridge.relay.1 {"val":1,"ack":true,"ts":1515871817836,"q":0,"from":"system.adapter.mqtt.0","lc":1515871730937}
mqtt.0 | 2018-01-13 20:30:17.837 | debug | Server received "RFBridge/relay/1" (number): 1

**Comment by Alveran81** [comment]
Das ist der Unterschied: system.adapter.admin.0 zu system.adapter.mqtt.0 

Könnte es daran liegen das nichts ankommt?

**Comment by Apollon77** [comment]
Also an sich sollte alles mit „ack=false“ gesendet werden. Bei ack=true (war bei deinem Lampen schalten überall) wird normalerweise nichts gesendet. Kannst du in den Einstellungen vom Adapter ändern. Wo kommt das mit ack=true her?

In „from“ wird der „Auslöser“ der Änderung angezeigt. Wenn also System.adapter.mqtt.0 steht kam die Änderung direkt von der mqtt.0 Instanz. Sonst siehst du wo die Änderung herkam.

**Comment by Apollon77** [comment]
OK ... ack=true kam vom device also vom mqtt. Passt also. Das log zeigt das der Adapter mal die Änderung gesehen hat und was getan hat. Warum das pot nicht ankommt weiß nicht.

**Comment by Alveran81** [comment]
OK. Aber alles was von system.adapter.admin.0 gesendet wird kommt nicht an. Wird es von system.adapter.mqtt.0 gesendet kommt es an.
Warum wird es überhaubt unterschiedlich gesendet? Ich ändere den Wert immer gleich unter Objekte. Aber alles was im unterordner ist wird von system.adapter.admin.0 gesendet.

**Comment by Apollon77** [comment]
Ich nutze kein mqtt daher kann ich dazu nichts sagen. 

Alles was ein from „System.adapter.mqtt“ hat sind EMPFANGENE Daten!! Deswegen haben die auch ein ack true. 

Alles was System.adapter.admin hat sind Änderungen die du per Admin machst. Deswegen sind das ack false, also steuerkommandos. 

So würde ich es verstehen und so ist der unterscheid erstmal klar. 

Am besten, weil crash ist weg, machen wir hier Schluss und im Forum weiter weil da ggf mehr Leute sind die sich mir mqtt auskennen ;-)

**Comment by Alveran81** [comment]
Ich muss nochmal kurz stören. Im Forum antwortet keiner.
Ich habe mir extra einen zweiten Raspberry organisiert iobroker frisch installiert und nur den MQTT Adapter installiert und das verhalten ist genau das gleiche. Es muss also am MQTT Adapter liegen.

**Comment by Apollon77** [comment]
Ich kenne mich mit MQTT kein bissl aus und habe es auch nicht im Einsatz ... Habe keine Idee wie ich da rangehen sollte. Versuch es bitte weiter im Forum Sorry

**Comment by GermanBluefox** [comment]
Wo ist die Frage im Forum?

16 янв. 2018 г. 21:28 пользователь "Ingo Fischer" <notifications@github.com>
написал:

**Comment by Alveran81** [comment]
http://forum.iobroker.net/viewtopic.php?f=20&t=10710

Bin gerade im Urlaub. Kann also nicht testen.

**Comment by Apollon77** [comment]
Eine Vermutung ist entstanden, siee auch #13 und so. Bitte mal prüfen welchen Datentyp die zu sendenden Objekte haben die nicht gehen. Ist es "mixed"? Wenn ja bitte mal auf den korrekten Typ stellen. geht es dann?

**Comment by GermanBluefox** [comment]
Gibt es was neues?

**Comment by Alveran81** [comment]
Ja aber es ist kompliziert. Der Adapter läuft ohne abzustürzen. Allerdings werden selbst angelegte Kommandos unter Iobroker/Objekte/mqtt.0 laut Wireshark nicht gesendet.

**Comment by GermanBluefox** [comment]
Bitte mit 2.0.1 probieren
